# Generated by Django 5.2.17 on 2026-09-23 10:00

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models

import banking.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=13, unique=True)),
                ("national_id", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "account_number",
                    models.CharField(
                        default=banking.models.account_number,
                        editable=False,
                        max_length=14,
                        unique=True,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("SAVINGS", "Savings"), ("CURRENT", "Current")],
                        default="SAVINGS",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(default="KES", editable=False, max_length=3)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DORMANT", "Dormant"),
                            ("CLOSED", "Closed"),
                        ],
                        default="ACTIVE",
                        max_length=8,
                    ),
                ),
                ("last_activity_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="banking.customer",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("operate_accounts", "Operate accounts as teller"),
                    ("manage_accounts", "Manage dormancy, closure and loans"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "loan_number",
                    models.CharField(
                        default=banking.models.loan_number,
                        editable=False,
                        max_length=14,
                        unique=True,
                    ),
                ),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10000.00"), max_digits=14
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10000.00"), max_digits=14
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DISBURSED", "Disbursed"),
                            ("REPAID", "Repaid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("disbursed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bank_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan",
                        to="banking.bankaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("reference", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("OPENING", "Account opened"),
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("TRANSFER_IN", "Transfer received"),
                            ("TRANSFER_OUT", "Transfer sent"),
                            ("LOAN_DISBURSEMENT", "Loan disbursed"),
                            ("ACCOUNT_CLOSURE", "Account closed"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("balance_before", models.DecimalField(decimal_places=2, max_digits=14)),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=14)),
                ("description", models.CharField(blank=True, max_length=240)),
                (
                    "transfer_group_reference",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="banking.bankaccount",
                    ),
                ),
                (
                    "related_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="related_entries",
                        to="banking.bankaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)), name="account_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency", "KES")), name="account_kes_only"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "DORMANT", "CLOSED"])),
                name="account_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("account_type__in", ["SAVINGS", "CURRENT"])),
                name="account_valid_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("principal_amount", 10000)), name="loan_fixed_principal"
            ),
        ),
        migrations.AddConstraint(
            model_name="loanaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outstanding_balance__gte", 0), ("outstanding_balance__lte", 10000)
                ),
                name="loan_outstanding_range",
            ),
        ),
        migrations.AddIndex(
            model_name="transactionentry",
            index=models.Index(
                fields=["account", "created_at"], name="banking_tra_account_ecb452_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("amount", 0),
                        ("balance_after", 0),
                        ("balance_before", 0),
                        ("transaction_type__in", ["OPENING", "ACCOUNT_CLOSURE"]),
                    ),
                    models.Q(
                        ("amount__gt", 0),
                        (
                            "transaction_type__in",
                            [
                                "DEPOSIT",
                                "WITHDRAWAL",
                                "TRANSFER_IN",
                                "TRANSFER_OUT",
                                "LOAN_DISBURSEMENT",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="ledger_valid_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance_after__gte", 0), ("balance_before__gte", 0)),
                name="ledger_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="transactionentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("balance_after", models.F("balance_before")),
                        ("transaction_type__in", ["OPENING", "ACCOUNT_CLOSURE"]),
                    ),
                    models.Q(
                        (
                            "balance_after",
                            django.db.models.expressions.CombinedExpression(
                                models.F("balance_before"), "+", models.F("amount")
                            ),
                        ),
                        ("transaction_type__in", ["DEPOSIT", "TRANSFER_IN", "LOAN_DISBURSEMENT"]),
                    ),
                    models.Q(
                        (
                            "balance_after",
                            django.db.models.expressions.CombinedExpression(
                                models.F("balance_before"), "-", models.F("amount")
                            ),
                        ),
                        ("transaction_type__in", ["WITHDRAWAL", "TRANSFER_OUT"]),
                    ),
                    _connector="OR",
                ),
                name="ledger_balances_match",
            ),
        ),
    ]
