# Generated by Django 5.2.17 on 2026-09-23 10:04

import django.db.models.expressions
import django.db.models.functions.math
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transactionentry",
            name="ledger_balances_match",
        ),
        migrations.AddConstraint(
            model_name="transactionentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("balance_after", models.F("balance_before")),
                        ("transaction_type__in", ["OPENING", "ACCOUNT_CLOSURE"]),
                    ),
                    models.Q(
                        (
                            "balance_after",
                            django.db.models.functions.math.Round(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("balance_before"), "+", models.F("amount")
                                ),
                                2,
                            ),
                        ),
                        ("transaction_type__in", ["DEPOSIT", "TRANSFER_IN", "LOAN_DISBURSEMENT"]),
                    ),
                    models.Q(
                        (
                            "balance_after",
                            django.db.models.functions.math.Round(
                                django.db.models.expressions.CombinedExpression(
                                    models.F("balance_before"), "-", models.F("amount")
                                ),
                                2,
                            ),
                        ),
                        ("transaction_type__in", ["WITHDRAWAL", "TRANSFER_OUT"]),
                    ),
                    _connector="OR",
                ),
                name="ledger_balances_match",
            ),
        ),
    ]
